import ClassicCard from "../../../components/card/ClassicCard";
import { ClassicTable } from "../../../components/tables/ClassicTable";
import { columns, data } from "../../../constants/mockData";

const Reports = () => {
    return (
        <div className="min-h-screen text-gray-800">
            <div className="">
                {/* Tabs */}
                <div className="flex space-x-8 border-b border-gray-200 mb-6">
                    <button className="pb-2 border-b-2 border-blue-600 text-blue-600 font-medium">Staff Work Report</button>
                    <button className="pb-2 text-gray-500 hover:text-blue-600 transition-colors">Client Billing Report</button>
                </div>

                {/* Header */}
                <div className="mb-6">
                    <h2 className="text-2xl font-semibold mb-1">Staff Work Report</h2>
                    <p className="text-gray-500 text-sm">View hours worked, staff costs, and revenue generated by employee and client</p>
                </div>

                {/* Filters */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                    <div>
                        <label className="block text-sm font-medium text-gray-600 mb-1">Start Date</label>
                        <input
                            type="date"
                            className="w-full border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-600 mb-1">End Date</label>
                        <input
                            type="date"
                            className="w-full border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-600 mb-1">Filter by Staff</label>
                        <select className="w-full border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-blue-500">
                            <option>test</option>
                            <option>John</option>
                        </select>
                    </div>

                    <div className="flex items-end gap-2">
                        <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 rounded-lg transition-colors">
                            Generate Report
                        </button>
                        <button className="w-full bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold py-2 rounded-lg transition-colors">
                            Export CSV
                        </button>
                    </div>
                </div>

                <ClassicTable columns={columns} data={data} />

                {/* Summary */}
                <div className="mt-10">
                    <h3 className="text-lg font-semibold mb-4">Summary</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                        <ClassicCard value="0.02" label="Total Hours" />
                        <ClassicCard value="$0.83" label="Total Staff Cost" />
                        <ClassicCard value="$1.17" label="Total Revenue" />
                        <div className="bg-green-100 rounded-xl p-4 text-center shadow-sm">
                            <p className="text-sm text-green-600 font-medium">Net Profit</p>
                            <p className="text-2xl font-bold text-green-700">$0.33</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Reports;
